/**
 * EcoForge AI — Circular Recommendation Catalog
 * 
 * Comprehensive knowledge base of circular economy interventions across 9 categories.
 * Primary Ownership: Member 3 (Circular Recommendation & AI Copilot)
 */

export const RECOMMENDATION_CATEGORIES = {
  ALTERNATIVE_MATERIALS: 'Alternative Materials',
  RECYCLED_MATERIALS: 'Recycled Materials',
  MATERIAL_REUSE: 'Material Reuse',
  RECYCLING_LOOPS: 'Recycling Loops',
  WASTE_TO_VALUE: 'Waste-to-Value',
  PROCESS_CHANGES: 'Process Changes',
  ENERGY_OPTIMIZATION: 'Energy Optimization',
  RENEWABLE_ENERGY_SUBSTITUTION: 'Renewable Energy Substitution',
  TRANSPORTATION_OPTIMIZATION: 'Transportation Optimization',
};

export const RECOMMENDATION_CATALOG = [
  // 1. Renewable Energy Substitution
  {
    id: 'REC-RENEWABLE-SOLAR-001',
    title: 'On-Site Rooftop Solar PV Installation',
    category: RECOMMENDATION_CATEGORIES.RENEWABLE_ENERGY_SUBSTITUTION,
    targetHotspot: 'electricity',
    description: 'Transition grid electricity consumption to clean, zero-emission on-site solar photovoltaic generation.',
    currentSituation: 'High reliance on conventional grid electricity with fossil fuel carbon intensity.',
    proposedAction: 'Install a captive rooftop solar PV array to cover 35–50% of base electricity demand.',
    whyRecommended: 'Electricity is a primary emission leak point. Solar PV offers reliable long-term emission reduction and electricity tariff hedging.',
    reductionPercentage: 40, // 40% reduction in electricity emissions
    unitSavingsINRPerKWh: 3.5, // Savings per kWh generated vs grid tariff
    implementationCostPerKWpINR: 45000, // Estimated capex per kWp
    paybackPeriodYears: 3.8,
    feasibility: 'High',
    difficulty: 'Moderate',
    priority: 'High',
    assumptions: 'Assumes suitable unshaded roof space of ~10 sq.m per kWp and 300 sunny days per year.',
    applicableIndustries: ['all'],
    applicableInputs: ['electricity'],
  },
  {
    id: 'REC-RENEWABLE-BIOMASS-002',
    title: 'Biomass Boiler Conversion for Process Heating',
    category: RECOMMENDATION_CATEGORIES.RENEWABLE_ENERGY_SUBSTITUTION,
    targetHotspot: 'coal',
    description: 'Replace fossil coal/heavy oil boilers with agricultural residue biomass briquette fuel.',
    currentSituation: 'Using high-emission coal or heavy fuel oil for steam generation and thermal heating.',
    proposedAction: 'Retrofit existing boiler burners or install a dedicated biomass briquette boiler system.',
    whyRecommended: 'Coal combustion generates carbon-dense emissions. Agricultural briquettes are carbon-neutral biomass alternatives.',
    reductionPercentage: 75,
    unitSavingsINRPerTonFuel: 2500,
    implementationCostPerKWpINR: 1200000,
    paybackPeriodYears: 2.5,
    feasibility: 'High',
    difficulty: 'Moderate',
    priority: 'High',
    assumptions: 'Assumes reliable regional supply chain for agro-briquettes (mustard husk, bagasse, groundnut shells).',
    applicableIndustries: ['textiles', 'chemical', 'food_processing', 'paper', 'manufacturing'],
    applicableInputs: ['coal', 'diesel'],
  },

  // 2. Energy Optimization
  {
    id: 'REC-ENERGY-VFD-003',
    title: 'Variable Frequency Drives (VFD) on Heavy Motors & Pumps',
    category: RECOMMENDATION_CATEGORIES.ENERGY_OPTIMIZATION,
    targetHotspot: 'electricity',
    description: 'Install intelligent VFD controllers on large motor drives, cooling towers, and fluid pumps.',
    currentSituation: 'Fixed-speed motors running at full load continuously despite variable operational demand.',
    proposedAction: 'Retrofit VFD drives with automated sensor feedback to match motor speed with real-time throughput demand.',
    whyRecommended: 'Reduces auxiliary electrical energy consumption by 20–30% with minimal footprint changes.',
    reductionPercentage: 25,
    unitSavingsINRPerKWh: 4.0,
    implementationCostPerKWpINR: 250000,
    paybackPeriodYears: 1.4,
    feasibility: 'High',
    difficulty: 'Easy',
    priority: 'High',
    assumptions: 'Assumes existing induction motors are compatible with inverter-duty VFD retrofits.',
    applicableIndustries: ['all'],
    applicableInputs: ['electricity'],
  },
  {
    id: 'REC-ENERGY-HEAT-RECOVERY-004',
    title: 'Waste Heat Recovery System (WHRS) from Exhaust Flue Gases',
    category: RECOMMENDATION_CATEGORIES.ENERGY_OPTIMIZATION,
    targetHotspot: 'natural_gas',
    description: 'Capture thermal energy from furnace flue gas or generator exhaust to preheat boiler feed water or process air.',
    currentSituation: 'High-temperature flue gases vented directly to atmosphere, losing significant sensible thermal energy.',
    proposedAction: 'Install a economizer heat exchanger or recuperator in exhaust stacks.',
    whyRecommended: 'Directly lowers natural gas / fuel consumption by recirculating recovered thermal calories into incoming feeds.',
    reductionPercentage: 18,
    unitSavingsINRPerTonFuel: 3000,
    implementationCostPerKWpINR: 850000,
    paybackPeriodYears: 2.1,
    feasibility: 'Medium',
    difficulty: 'Moderate',
    priority: 'High',
    assumptions: 'Flue gas temperature exceeds 180°C and process operates >16 hours/day.',
    applicableIndustries: ['chemical', 'metal_working', 'ceramics', 'glass', 'textiles'],
    applicableInputs: ['natural_gas', 'diesel', 'coal'],
  },

  // 3. Alternative Materials
  {
    id: 'REC-MAT-BIO-PLASTIC-005',
    title: 'Bio-Based Polymers & Low-Carbon Raw Material Substitution',
    category: RECOMMENDATION_CATEGORIES.ALTERNATIVE_MATERIALS,
    targetHotspot: 'raw_materials',
    description: 'Replace fossil-based virgin synthetic polymers with bio-based PLA/PHA or low-carbon composite resin.',
    currentSituation: '100% virgin petroleum-derived polymer inputs with high cradle-to-gate embedded carbon emissions.',
    proposedAction: 'Formulate product compounds using 30–50% bio-based or plant-derived resin feeds.',
    whyRecommended: 'Virgin raw materials account for a major fraction of scope 3 embedded emissions. Bio-polymers reduce carbon intensity per kg produced.',
    reductionPercentage: 35,
    unitSavingsINRPerTonFuel: 1500,
    implementationCostPerKWpINR: 150000,
    paybackPeriodYears: 2.8,
    feasibility: 'Medium',
    difficulty: 'Moderate',
    priority: 'Medium',
    assumptions: 'Assumes mechanical tensile property standards are validated with bio-composite blends.',
    applicableIndustries: ['packaging', 'plastics', 'automotive', 'consumer_goods'],
    applicableInputs: ['raw_materials', 'virgin_materials'],
  },
  {
    id: 'REC-MAT-FLYASH-CEMENT-006',
    title: 'Pozzolanic Fly Ash / Slag Blending in Concrete Formulations',
    category: RECOMMENDATION_CATEGORIES.ALTERNATIVE_MATERIALS,
    targetHotspot: 'raw_materials',
    description: 'Substitute Ordinary Portland Cement (OPC) with industrial fly ash or ground granulated blast-furnace slag (GGBS).',
    currentSituation: 'High cement clinker content in construction products driving calcination and thermal emissions.',
    proposedAction: 'Adopt Portland Pozzolana Cement (PPC) or blend up to 35% fly ash into industrial batches.',
    whyRecommended: 'Cement calcination is a massive carbon hotspot. Industrial byproduct substitution yields strong carbon and cost reduction.',
    reductionPercentage: 30,
    unitSavingsINRPerTonFuel: 800,
    implementationCostPerKWpINR: 80000,
    paybackPeriodYears: 0.9,
    feasibility: 'High',
    difficulty: 'Easy',
    priority: 'High',
    assumptions: 'Fly ash meets ASTM C618 / IS 3812 quality specifications.',
    applicableIndustries: ['construction', 'building_materials', 'infrastructure'],
    applicableInputs: ['raw_materials'],
  },

  // 4. Recycled Materials
  {
    id: 'REC-RECYCLED-RESIN-007',
    title: 'Post-Consumer Recycled (PCR) Polymer Incorporation',
    category: RECOMMENDATION_CATEGORIES.RECYCLED_MATERIALS,
    targetHotspot: 'raw_materials',
    description: 'Replace virgin HDPE/PET/PP polymers with certified post-consumer recycled (PCR) pellets.',
    currentSituation: 'Manufacturing processes consume 100% virgin plastic resin.',
    proposedAction: 'Transition feedstock to 40% PCR resin content without compromising structural integrity.',
    whyRecommended: 'PCR resin has up to 70% lower embedded carbon than virgin petroleum polymer.',
    reductionPercentage: 32,
    unitSavingsINRPerTonFuel: 4500,
    implementationCostPerKWpINR: 300000,
    paybackPeriodYears: 1.8,
    feasibility: 'High',
    difficulty: 'Moderate',
    priority: 'High',
    assumptions: 'PCR resin quality meets melt flow index (MFI) and color clarity requirements.',
    applicableIndustries: ['packaging', 'plastics', 'consumer_goods'],
    applicableInputs: ['raw_materials', 'virgin_materials'],
  },
  {
    id: 'REC-RECYCLED-SCRAP-008',
    title: 'High-Fraction Recycled Scrap Metal Feedstock Integration',
    category: RECOMMENDATION_CATEGORIES.RECYCLED_MATERIALS,
    targetHotspot: 'raw_materials',
    description: 'Increase secondary aluminum / steel scrap ratio in induction melting operations.',
    currentSituation: 'Primary virgin metal ingots used as primary feed in casting and fabrication.',
    proposedAction: 'Increase secondary scrap charge fraction to 60–80% in melting furnaces.',
    whyRecommended: 'Recycling aluminum requires only ~5% of the energy needed for primary smelting from bauxite.',
    reductionPercentage: 65,
    unitSavingsINRPerTonFuel: 12000,
    implementationCostPerKWpINR: 500000,
    paybackPeriodYears: 1.2,
    feasibility: 'High',
    difficulty: 'Easy',
    priority: 'High',
    assumptions: 'Scrap sorting equipment ensures alloy purity standards.',
    applicableIndustries: ['metal_working', 'foundry', 'automotive', 'machinery'],
    applicableInputs: ['raw_materials', 'virgin_materials'],
  },

  // 5. Recycling Loops
  {
    id: 'REC-LOOP-SOLVENT-009',
    title: 'Closed-Loop On-Site Solvent Recovery & Distillation',
    category: RECOMMENDATION_CATEGORIES.RECYCLING_LOOPS,
    targetHotspot: 'waste',
    description: 'Install vacuum batch distillation units to purify and reuse spent industrial solvents on-site.',
    currentSituation: 'Spent solvents (IPA, Acetone, Toluene) disposed of as hazardous waste streams.',
    proposedAction: 'Recover up to 90% of spent solvent for immediate re-entry into cleaning/reaction processes.',
    whyRecommended: 'Eliminates hazardous waste incineration emissions while eliminating virgin solvent purchasing costs.',
    reductionPercentage: 55,
    unitSavingsINRPerTonFuel: 25000,
    implementationCostPerKWpINR: 600000,
    paybackPeriodYears: 1.1,
    feasibility: 'High',
    difficulty: 'Moderate',
    priority: 'High',
    assumptions: 'Distillate purity reaches process grade (≥98.5%).',
    applicableIndustries: ['chemical', 'pharmaceutical', 'paints', 'electronics'],
    applicableInputs: ['waste', 'raw_materials'],
  },
  {
    id: 'REC-LOOP-WATER-010',
    title: 'Zero Liquid Discharge (ZLD) Process Water Recirculation',
    category: RECOMMENDATION_CATEGORIES.RECYCLING_LOOPS,
    targetHotspot: 'waste',
    description: 'Implement Reverse Osmosis (RO) and MVR evaporator loops to recover process wash water.',
    currentSituation: 'Process wastewater treated externally or discharged, requiring constant fresh water extraction.',
    proposedAction: 'Filter and recycle 85% of process effluent back into boiler feed and wash tanks.',
    whyRecommended: 'Reduces Scope 3 water handling emissions and protects against raw water supply disruptions.',
    reductionPercentage: 40,
    unitSavingsINRPerTonFuel: 15000,
    implementationCostPerKWpINR: 1100000,
    paybackPeriodYears: 2.6,
    feasibility: 'Medium',
    difficulty: 'Complex',
    priority: 'Medium',
    assumptions: 'Effluent TDS levels are suitable for RO concentration.',
    applicableIndustries: ['textiles', 'tannery', 'chemical', 'food_processing'],
    applicableInputs: ['waste', 'electricity'],
  },

  // 6. Material Reuse
  {
    id: 'REC-REUSE-PACKAGING-011',
    title: 'Standardized Closed-Loop Returnable Container Systems',
    category: RECOMMENDATION_CATEGORIES.MATERIAL_REUSE,
    targetHotspot: 'raw_materials',
    description: 'Replace single-use wooden pallets and corrugated paper boxes with heavy-duty collapsible returnable crates.',
    currentSituation: 'Continuous purchasing and disposal of single-use shipping containers and packaging.',
    proposedAction: 'Deploy standardized HDPE returnable crates with logistics tracking.',
    whyRecommended: 'Eliminates recurring packaging waste generation and avoids single-use embodied manufacturing carbon.',
    reductionPercentage: 45,
    unitSavingsINRPerTonFuel: 6000,
    implementationCostPerKWpINR: 350000,
    paybackPeriodYears: 1.5,
    feasibility: 'High',
    difficulty: 'Easy',
    priority: 'High',
    assumptions: 'Logistics network allows >90% container return rate from distribution hubs.',
    applicableIndustries: ['all'],
    applicableInputs: ['raw_materials', 'waste', 'transport'],
  },

  // 7. Waste-to-Value
  {
    id: 'REC-WASTE-BIOGAS-012',
    title: 'Anaerobic Digestion of Organic Process Waste to Biogas',
    category: RECOMMENDATION_CATEGORIES.WASTE_TO_VALUE,
    targetHotspot: 'waste',
    description: 'Convert organic food sludge or agro-waste into methane biogas for boiler fuel or power generation.',
    currentSituation: 'Organic waste sent to municipal landfills, emitting uncaptured fugitive methane.',
    proposedAction: 'Install a bio-methanation plant on-site to generate thermal biogas.',
    whyRecommended: 'Transforms a costly waste disposal liability into a high-value renewable fuel stream.',
    reductionPercentage: 70,
    unitSavingsINRPerTonFuel: 18000,
    implementationCostPerKWpINR: 1500000,
    paybackPeriodYears: 2.9,
    feasibility: 'Medium',
    difficulty: 'Complex',
    priority: 'High',
    assumptions: 'Daily organic waste stream exceeds 1.5 metric tons.',
    applicableIndustries: ['food_processing', 'beverage', 'agriculture', 'dairy'],
    applicableInputs: ['waste', 'natural_gas'],
  },

  // 8. Process Changes
  {
    id: 'REC-PROC-OPTIM-013',
    title: 'Low-Temperature Process Washing & Enzymatic Scouring',
    category: RECOMMENDATION_CATEGORIES.PROCESS_CHANGES,
    targetHotspot: 'natural_gas',
    description: 'Transition thermal scouring and degreasing baths from 95°C to 45°C using enzymatic biocatalysts.',
    currentSituation: 'High thermal energy consumption for heating large liquid process baths.',
    proposedAction: 'Re-formulate chemical washing steps with low-temperature bio-enzymes.',
    whyRecommended: 'Directly slashes thermal boiler fuel demand while reducing cycle time and water consumption.',
    reductionPercentage: 35,
    unitSavingsINRPerTonFuel: 5000,
    implementationCostPerKWpINR: 120000,
    paybackPeriodYears: 0.6,
    feasibility: 'High',
    difficulty: 'Easy',
    priority: 'High',
    assumptions: 'Process specs permit 45°C washing duration.',
    applicableIndustries: ['textiles', 'metal_finishing', 'food_processing'],
    applicableInputs: ['natural_gas', 'coal', 'diesel'],
  },

  // 9. Transportation Optimization
  {
    id: 'REC-TRANS-FLEET-014',
    title: 'Commercial Fleet Electrification & Route AI Optimization',
    category: RECOMMENDATION_CATEGORIES.TRANSPORTATION_OPTIMIZATION,
    targetHotspot: 'diesel',
    description: 'Replace diesel logistics light commercial vehicles (LCVs) with Electric Commercial Vehicles (EVs) and smart routing.',
    currentSituation: 'High diesel fuel consumption from internal logistics and distribution trucks.',
    proposedAction: 'Deploy 3.5T electric delivery vans paired with AI-driven route consolidation.',
    whyRecommended: 'Diesel is a high-carbon combustion source. EVs offer ~60-70% reduction in tailpipe emissions depending on grid power mix.',
    reductionPercentage: 50,
    unitSavingsINRPerTonFuel: 8000, // per vehicle annual fuel saving vs EV charging
    implementationCostPerKWpINR: 800000,
    paybackPeriodYears: 3.2,
    feasibility: 'High',
    difficulty: 'Moderate',
    priority: 'High',
    assumptions: 'Daily route range < 180 km and depot charging infrastructure available.',
    applicableIndustries: ['all'],
    applicableInputs: ['diesel', 'transport'],
  },
  {
    id: 'REC-TRANS-LOCAL-015',
    title: 'Regional Supply Chain Localization & Intermodal Shift',
    category: RECOMMENDATION_CATEGORIES.TRANSPORTATION_OPTIMIZATION,
    targetHotspot: 'transport',
    description: 'Shift long-haul raw material procurement to regional suppliers within a 150 km radius.',
    currentSituation: 'Long-distance diesel road freight hauling raw materials across thousands of kilometers.',
    proposedAction: 'Qualify nearshore/local suppliers and switch freight from road trucks to electrified rail lines.',
    whyRecommended: 'Slashing freight ton-kilometers delivers dramatic Scope 3 transport emission drops.',
    reductionPercentage: 40,
    unitSavingsINRPerTonFuel: 7000,
    implementationCostPerKWpINR: 200000,
    paybackPeriodYears: 1.6,
    feasibility: 'Medium',
    difficulty: 'Moderate',
    priority: 'Medium',
    assumptions: 'Regional suppliers meet component technical standards.',
    applicableIndustries: ['all'],
    applicableInputs: ['transport', 'diesel'],
  },
];
